name: PHP Compatibility

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**/*.php'

jobs:
  php-compatibility:
    name: PHP Compatibility (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]

    steps:
      - uses: actions/checkout@v3

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            src:
              - added|modified: 'src/**/*.php'

      - name: Configure PHP environment
        uses: shivammathur/setup-php@v2
        if: ${{ steps.filter.outputs.src == 'true' }}
        with:
          php-version: 7.4
          extensions: mbstring, intl
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        if: ${{ steps.filter.outputs.src == 'true' }}
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: ramsey/composer-install@v2
        if: ${{ steps.filter.outputs.src == 'true' }}
        with:
          dependency-versions: highest

      - name: Run PHP Compatibility
        if: ${{ steps.filter.outputs.src == 'true' }}
        run: phpcs ${{ steps.filter.outputs.wpcontent_files }} -s --standard=PHPCompatibilityWP --runtime-set testVersion ${{ matrix.php-version }}
